// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jpwcyxoxpkcnhrdojxvs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impwd2N5eG94cGtjbmhyZG9qeHZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAzMTk5NzIsImV4cCI6MjA1NTg5NTk3Mn0.2C0B3dYiP6HUU8mcyktMn1P8U2bCKVYcqIHHClnL-Nw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);